### ISSUE TITLE
Replacement

### ISSUE THREAD

**Issue by galulex** [galulex/timetable#2]
1. Create replacement table with fields that lessons table has plus lesson_id, date
2. When schedule is published add replacement button.
3. Replacement controller similar to lessons controller
4. Form for creating replacement similar to lessons form plus date select for date when we need to replace the lesson

**Comment by Alexey-Lukin** [comment]
Replacement functionality done, need to add replacement button, not clear for me where to add it, please call to me Alex to clarify this.

**Comment by galulex** [comment]
When schedule is published we are not able to edit lessons. Replacement link should be in lesson partial and show it when schedule is published.
