### ISSUE TITLE
Clone lesson

### ISSUE THREAD

**Issue by galulex** [galulex/timetable#4]
1. Add button 'copy' to lesson partial
2. Add action copy to lesson controller and route with get request
3. Put lesson id to session: session[:lesson_id] = lesson.id
4. Show paste button in empty schedule fields when lesson_id is stored to session
5. Add action paste to lessons controller with post request
6. Clone all data from lesson that is stored to session

**Comment by Alexey-Lukin** [comment]
Will be done on Sunday
